"""bundle id

Revision ID: 9541084431a3
Revises: 
Create Date: 2022-10-25 12:51:37.690693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9541084431a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency_pair', sa.Column('pair', sa.String(), nullable=False))
    op.add_column('currency_pair', sa.Column('rate', sa.Numeric(), nullable=False))
    op.add_column('currency_pair', sa.Column('bundle_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'currency_pair', 'bundle', ['bundle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'currency_pair', type_='foreignkey')
    op.drop_column('currency_pair', 'bundle_id')
    op.drop_column('currency_pair', 'rate')
    op.drop_column('currency_pair', 'pair')
    # ### end Alembic commands ###
